# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[7.1.0 7.2.0 8.0.0].each do |version|
  appraise "delayed_job_4.1-activejob-#{version}" do
    gem 'delayed_job', '~> 4.1'
    gem 'activejob', "~> #{version}"
  end
end

appraise 'delayed_job-latest' do
  gem 'delayed_job'
  gem 'activejob'
end
