# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[7.1.0 7.2.0 8.1.3.1].each do |version|
  appraise "activejob-#{version}" do
    gem 'activejob', "~> #{version}"
    gem 'delayed_job', '= 4.2.0'
  end
end

%w[4.1.0 4.2.0].each do |version|
  appraise "delayed_job-#{version}" do
    gem 'delayed_job', "~> #{version}"
    gem 'activejob', '= 8.1.3.1'
    gem 'benchmark', '= 0.5.0'
  end
end
