# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'appraisal', '~> 2.5'
  gem 'minitest', '~> 5.0'
  gem 'opentelemetry-sdk', '~> 1.1'
  gem 'opentelemetry-test-helpers', '~> 0.3'
  gem 'rubocop', '~> 1.82.0'
  gem 'rubocop-performance', '~> 1.26.0'
  gem 'simplecov', '~> 0.22.0'
  gem 'webmock', '~> 3.24'
  gem 'yard', '~> 0.9'
  gem 'rspec-mocks', '~> 3.13.7'
  gem 'sqlite3', '~> 2.9'
  gem 'opentelemetry-instrumentation-base', path: '../base'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'mutex_m'
  end
  # https://github.com/collectiveidea/delayed_job/issues/1245
  gem 'ostruct' if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('4')
end
