# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gem 'sqlite3', platforms: [:ruby, :jruby, :x64_mingw]

gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', path: '../base'
end
