# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'delayed_job', '~> 4.1'
  gem 'opentelemetry-instrumentation-base', path: '../base'
end
