# frozen_string_literal: true

source 'https://rubygems.org'

gem 'net-ldap'
gem 'opentelemetry-api'
gem 'opentelemetry-common'
gem 'opentelemetry-instrumentation-base'
gem 'opentelemetry-instrumentation-net_ldap', path: '../'
gem 'opentelemetry-sdk'
