# frozen_string_literal: true

# Last release 1.4.6 (February 26, 2023)
appraise 'pg-1.4' do
  gem 'pg', '~> 1.4'
end

appraise 'pg-1.5' do
  gem 'pg', '~> 1.5'
end

appraise 'pg-latest' do
  gem 'pg'
end
