# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('3.4')
  appraise 'gruf-2.19' do
    gem 'gruf', '~> 2.19.0'
  end
end

if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('3.5')
  appraise 'gruf-2.20' do
    gem 'gruf', '~> 2.20.0'
  end

  appraise 'gruf-2.21' do
    gem 'gruf', '~> 2.21.0'
  end
end

appraise 'gruf-latest' do
  gem 'gruf'
end
