# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'gruf-2.15.1' do
  gem 'gruf', '~> 2.15.1'
end

appraise 'gruf-2.16.1' do
  gem 'gruf', '~> 2.16.1'
end
