# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'appraisal', '~> 2.5'
  gem 'bundler', '~> 2.4'
  gem 'minitest', '~> 5.0'
  gem 'opentelemetry-sdk', '~> 1.1'
  gem 'opentelemetry-test-helpers', '~> 0.3'
  gem 'rack-test', '~> 2.2.0'
  gem 'rake', '~> 13.0'
  gem 'rubocop', '~> 1.81.1'
  gem 'rubocop-performance', '~> 1.26.0'
  gem 'simplecov', '~> 0.22.0'
  gem 'webmock', '~> 3.24'
  gem 'yard', '~> 0.9'

  gem 'opentelemetry-instrumentation-base', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/base/*.gemspec'
  gem 'opentelemetry-instrumentation-concurrent_ruby', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/concurrent_ruby/*.gemspec'
  gem 'opentelemetry-instrumentation-active_job', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/active_job/*.gemspec'
  gem 'opentelemetry-instrumentation-action_mailer', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/action_mailer/*.gemspec'
  gem 'opentelemetry-instrumentation-action_pack', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/action_pack/*.gemspec'
  gem 'opentelemetry-instrumentation-active_record', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/active_record/*.gemspec'
  gem 'opentelemetry-instrumentation-active_support', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/active_support/*.gemspec'
  gem 'opentelemetry-instrumentation-active_storage', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/active_storage/*.gemspec'
  gem 'opentelemetry-instrumentation-action_view', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/action_view/*.gemspec'
  gem 'opentelemetry-instrumentation-rack', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/rack/*.gemspec'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'drb'
    gem 'mutex_m'
  end
end
