# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test, :development do
  gem 'pry-byebug'
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'opentelemetry-instrumentation-concurrent_ruby', path: '../concurrent_ruby'
  gem 'opentelemetry-instrumentation-active_job', path: '../active_job'
  gem 'opentelemetry-instrumentation-action_mailer', path: '../action_mailer'
  gem 'opentelemetry-instrumentation-action_pack', path: '../action_pack'
  gem 'opentelemetry-instrumentation-active_record', path: '../active_record'
  gem 'opentelemetry-instrumentation-active_support', path: '../active_support'
  gem 'opentelemetry-instrumentation-action_view', path: '../action_view'
  gem 'opentelemetry-instrumentation-rack', path: '../rack'
  gem 'mutex_m' if RUBY_VERSION >= '3.4'
end
