# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'appraisal', '~> 2.5.0'
  gem 'minitest', '~> 6.0.0'
  gem 'opentelemetry-sdk', '~> 1.12.0'
  gem 'opentelemetry-test-helpers', '~> 0.9.0'
  gem 'rack-test', '~> 2.2.0'
  gem 'rake', '>= 13'
  gem 'rubocop', '~> 1.88.0'
  gem 'rubocop-performance', '~> 1.26.0'
  gem 'simplecov', '~> 0.22.0'
  gem 'webmock', '~> 3.26.0'
  gem 'yard', '~> 0.9.0'
  gem 'rbs', '4.1.0.pre.2', platforms: :jruby

  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'opentelemetry-instrumentation-concurrent_ruby', path: '../concurrent_ruby'
  gem 'opentelemetry-instrumentation-active_job', path: '../active_job'
  gem 'opentelemetry-instrumentation-action_mailer', path: '../action_mailer'
  gem 'opentelemetry-instrumentation-action_pack', path: '../action_pack'
  gem 'opentelemetry-instrumentation-active_record', path: '../active_record'
  gem 'opentelemetry-instrumentation-active_support', path: '../active_support'
  gem 'opentelemetry-instrumentation-active_storage', path: '../active_storage'
  gem 'opentelemetry-instrumentation-action_view', path: '../action_view'
  gem 'opentelemetry-instrumentation-rack', path: '../rack'
  # workaround for https://github.com/ruby/rdoc/issues/1746
  gem 'rbs', '4.1.0.pre.2', platforms: :jruby # TODO: remove once stable version is available
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'drb'
    gem 'mutex_m'
    gem 'logger'
  end
end
