# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[7.1.0 7.2.0 8.0.0 8.1.3.1].each do |version|
  appraise "action_mailer-#{version}" do
    gem 'rails', "= #{version}"
    gem 'benchmark', '= 0.5.0'
  end
end
