# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[7.1.0 7.2.0 8.0.0 8.1.0].each do |version|
  appraise "action_mailer-#{version}" do
    gem 'rails', "~> #{version}"

    # workaround for https://github.com/ruby/rdoc/issues/1746
    write_gemfile <<~RUBY
      ENV['RBS_DISABLE_EXT'] = 'true' if RUBY_ENGINE == 'jruby'
    RUBY
  end
end

appraise 'action_mailer-latest' do
  gem 'rails'

  # workaround for https://github.com/ruby/rdoc/issues/1746
  write_gemfile <<~RUBY
    ENV['RBS_DISABLE_EXT'] = 'true' if RUBY_ENGINE == 'jruby'
  RUBY
end
