# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'opentelemetry-instrumentation-active_support', path: '../active_support'
  # Add jar-dependencies gem only if the Ruby runtime is JRuby
  # https://github.com/jruby/jruby/issues/7262
  gem 'jar-dependencies', '0.4.1', platforms: :jruby
end
