# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'appraisal', '~> 2.5'
  gem 'bundler', '~> 2.4'
  gem 'minitest', '~> 5.0'
  gem 'opentelemetry-sdk', '~> 1.1'
  gem 'opentelemetry-test-helpers', '~> 0.3'
  gem 'rake', '~> 13.0'
  gem 'rubocop', '~> 1.81.1'
  gem 'rubocop-performance', '~> 1.26.0'
  gem 'simplecov', '~> 0.22.0'
  gem 'webmock', '~> 3.24'
  gem 'yard', '~> 0.9'
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'opentelemetry-instrumentation-active_support', path: '../active_support'
  # Add jar-dependencies gem only if the Ruby runtime is JRuby
  # https://github.com/jruby/jruby/issues/7262
  gem 'jar-dependencies', '0.4.1', platforms: :jruby
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'mutex_m'
  end
end
