# cSpell:ignore textlintrc
# For settings, see
# https://www.streetsidesoftware.com/vscode-spell-checker/docs/configuration/
version: '0.2'
caseSensitive: false
patterns:
  - name: CodeBlock
    pattern: |
      /
          ^(\s*[~`]{3,})   # code-block start
          .*               # all languages and options, e.g. shell {hl_lines=[12]}
          [\s\S]*?         # content
          \1               # code-block end
      /igmx
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - CodeBlock
words:
  - AWSX
  - Azuma
  - backports
  - behaviour
  - Bogsanyi
  - callables
  - circleci
  - Clientcontext
  - codeowners
  - dalli
  - datadog
  - enqueuers
  - ethon
  - excon
  - faas
  - fanout
  - faraday
  - gettime
  - gemfile
  - Gitter
  - gruf
  - hibachrach
  - HTTPX
  - httpx
  - instrumenter
  - Laurin
  - Lightstep
  - linux
  - lmdb
  - microbenchmarks
  - Mustin
  - myapp
  - namespacing
  - opentelemetry
  - otelcol
  - ottrace
  - postgres
  - postgresql
  - racecar
  - rabbitmq
  - Railtie
  - Rakefile
  - Reopelle
  - rdkafka
  - resque
  - restclient
  - Robb
  - rubocop
  - rubydocs
  - ruboproof
  - rubygems
  - Šimánek
  - semconv
  - sidekiq
  - sinatra
  - Solarwinds
  - spanid
  - toolset
  - traceid
  - traceresponse
  - Triager
  - triagers
  - Untrace
  - vitess
  - webmocks
  - Xuan
  - yardoc
  - traceparent