# cSpell:ignore textlintrc
# For settings, see
# https://www.streetsidesoftware.com/vscode-spell-checker/docs/configuration/
version: '0.2'
caseSensitive: false
import:
  - https://cdn.jsdelivr.net/npm/@cspell/dict-people-names/cspell-ext.json
ignorePaths:
  - 'bin'
  - '**.conf'
  - '**.gemspec'
  - '**.json'
  - '**.proto'
  - '**.rb'
  - '**.ru'
  - '**.yml'
  - 'Appraisals'
  - 'CODEOWNERS'
  - 'Dockerfile'
  - 'Gemfile'
  - 'Rakefile'
patterns:
  - name: CodeBlock
    pattern: |
      /
          ^(\s*[~`]{3,})   # code-block start
          .*               # all languages and options, e.g. shell {hl_lines=[12]}
          [\s\S]*?         # content
          \1               # code-block end
      /igmx
  - name: CodeName
    pattern: |
      /
          ([~`])          # Matches a single backtick or tilde to start a code block.
          [^~`]*?         # Matches any characters except backticks or tildes, non-greedy.
          \1              # Matches the same symbol which started the match.
      /x
  - name: "GitHub Handle"
    pattern: "@[a-zA-Z0-9-_]+\\b"
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - CodeBlock
      - CodeName
      - GitHub Handle
dictionaries:
  - aws
  - companies
  - people-names
  - ruby
  - softwareTerms
  - software-tools
words:
  - AWSXRayTrace
  - enqueuers
  - myapp
  - otelcol
  - ottrace
  - ruboproof
  - semconv
  - spanid
  - traceid
  - traceparent
  - traceresponse
  
  # Ruby
  - dalli
  - ethon
  - gruf
  - httpx
  - lmdb
  - Railtie
  - racecar
  - rdkafka
  - restclient
  - rubydocs