# linkspector config file is described at https://github.com/UmbrellaDocs/linkspector/blob/main/README.md#configuration
dirs:
  - .
excludedFiles:
excludedDirs:
ignorePatterns:
useGitIgnore: true
followRedirects: true
