# linkspector config file is described at https://github.com/UmbrellaDocs/linkspector/blob/main/README.md#configuration
dirs:
  - .
excludedDirs:
  - helpers/sql-obfuscation/
  - instrumentation/dalli/
  - instrumentation/mongo/
  - instrumentation/restclient/
  - instrumentation/ruby_kafka/
useGitIgnore: true
followRedirects: true
httpHeaders:
  - url:
      - https://cloud-native.slack.com
    headers:
      User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.9"
