AllCops:
  TargetRubyVersion: '2.7.6'
  Exclude:
    - Rakefile
    - "rakelib/**/*"
    - "**/example/*"
    - "bin/instrumentation_generator"
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "**/*test.rb"
Lint/MixedRegexpCaptureTypes:
  Exclude:
    - propagator/xray/lib/opentelemetry/propagator/xray/text_map_propagator.rb
Lint/UnusedMethodArgument:
  Enabled: false
Naming/FileName:
  Exclude:
    - '**/opentelemetry-*'
Naming/MethodParameterName:
  Exclude:
    - instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/patches/server.rb
Metrics/LineLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Naming/AsciiIdentifiers:
  Exclude:
    - 'instrumentation/sidekiq/**/*'
Style/AsciiComments:
  Exclude:
    - 'instrumentation/sidekiq/**/*'
Style/Documentation:
  Exclude:
    - "**/test/**/*"
    - "**/*test*"
Style/FrozenStringLiteralComment:
  Exclude:
    - "**/gemfiles/*"
Metrics/CyclomaticComplexity:
  Exclude:
    - "instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_tracer.rb"
Style/ModuleFunction:
  Enabled: false
Style/MultilineIfModifier:
  Exclude:
     - "**/test/**/*"
Style/RedundantRegexpEscape:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - "**/gemfiles/*"
Style/SlicingWithRange:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false

