AllCops:
  TargetRubyVersion: '2.7.6'
  NewCops: enable
  Exclude:
    - Rakefile
    - "rakelib/**/*"
    - "**/example/*"
    - "bin/instrumentation_generator"
    - "**/**/vendor/bundle/**/*"
Bundler/OrderedGems:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "**/*test.rb"
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Naming/FileName:
  Exclude:
    - '**/opentelemetry-*'
Style/Documentation:
  Exclude:
    - "**/test/**/*"
    - "**/*test*"
Style/FrozenStringLiteralComment:
  Exclude:
    - "**/gemfiles/*"
Style/ModuleFunction:
  Enabled: false
Style/MultilineIfModifier:
  Exclude:
     - "**/test/**/*"
Style/RedundantRegexpEscape:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - "**/gemfiles/*"
Style/SlicingWithRange:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
## 1.41.1
Gemspec/RequireMFA:
  # We probably want to figure out how to set this up for the organization
  Enabled: false
Layout/LineLength:
  Enabled: false
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false
Lint/EmptyBlock:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
Lint/RedundantRequireStatement:
  Enabled: false
Lint/SymbolConversion:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Style/CollectionCompact:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/HashConversion:
  Enabled: false
Style/QuotedSymbols:
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/SymbolProc:
  Enabled: false
