require: rubocop-performance

AllCops:
  TargetRubyVersion: '3.0'
  NewCops: enable
  Exclude:
    - Rakefile
    - "rakelib/**/*"
    - "**/example/*"
    - "bin/instrumentation_generator"
    - "**/**/vendor/bundle/**/*"
Bundler/OrderedGems:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "**/*test.rb"
Lint/EmptyBlock:
  Exclude:
    - "**/*test.rb"
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/FileName:
  Exclude:
    - '**/opentelemetry-*'
Style/Documentation:
  Exclude:
    - "**/test/**/*"
    - "**/*test*"
Style/FrozenStringLiteralComment:
  Exclude:
    - "**/gemfiles/*"
Style/ModuleFunction:
  Enabled: false
Style/MultilineIfModifier:
  Exclude:
     - "**/test/**/*"
Style/RedundantRegexpEscape:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - "**/gemfiles/*"
Style/SlicingWithRange:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
## 1.41.1
Gemspec/RequireMFA:
  # We probably want to figure out how to set this up for the organization
  Enabled: false
Layout/LineLength:
  Enabled: true
  Max: 250
