include:
  - ./.docker/volume/compose.yml
  - ./.docker/infra/kafka/docker-compose.yml
  - ./.docker/infra/memcached/docker-compose.yml
  - ./.docker/infra/mongo/docker-compose.yml
  - ./.docker/infra/mysql/docker-compose.yml
  - ./.docker/infra/postgres/docker-compose.yml
  - ./.docker/infra/rabbitmq/docker-compose.yml
  - ./.docker/infra/redis/docker-compose.yml

services:
  app:
    extends:
      service: base
      file: ./docker-base.yml
    build:
      context: .
    working_dir: /app
    depends_on:
      - kafka
      - jaeger
      - mysql
      - mongo
      - memcached
      - otelcol
      - postgres
      - rabbitmq
      - redis

  ex-instrumentation-bunny:
    extends:
      service: base
      file: ./docker-base.yml
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    working_dir: /app/instrumentation/bunny/example

  ex-instrumentation-concurrent-ruby:
    extends:
      service: base
      file: ./docker-base.yml
    working_dir: /app/instrumentation/concurrent_ruby/example

  ex-instrumentation-delayed_job:
    extends:
      service: base
      file: ./docker-base.yml
    working_dir: /app/instrumentation/delayed_job/example

  ex-instrumentation-ethon:
    extends:
      service: base
      file: ./docker-base.yml
    working_dir: /app/instrumentation/ethon/example

  ex-instrumentation-excon:
    extends:
      service: base
      file: ./docker-base.yml
    working_dir: /app/instrumentation/excon/example

  ex-instrumentation-faraday:
    extends:
      service: base
      file: ./docker-base.yml
    working_dir: /app/instrumentation/faraday/example

  ex-instrumentation-mysql2:
    extends:
      service: base
      file: ./docker-base.yml
    environment:
      - TEST_MYSQL_USER=root
      - TEST_MYSQL_ROOT_PASSWORD=root
      - TEST_MYSQL_HOST=mysql
      - TEST_MYSQL_PORT=3306
      - TEST_MYSQ_DB=mysql
    depends_on:
      - mysql
    working_dir: /app/instrumentation/mysql2/example

  ex-instrumentation-mysql2-test:
    extends:
      service: base
      file: ./docker-base.yml
    depends_on:
      - mysql
    working_dir: /app/instrumentation/mysql2/

  ex-instrumentation-pg:
    extends:
      service: base
      file: ./docker-base.yml
    environment:
      - TEST_POSTGRES_PASSWORD=postgres
      - TEST_POSTGRES_USER=postgres
      - TEST_POSTGRES_HOST=postgres
      - TEST_POSTGRES_PORT=5432
      - TEST_POSTGRES_DB=postgres
      - OTEL_TRACES_EXPORTER=console
    depends_on:
      - postgres
    working_dir: /app/instrumentation/pg/example

  ex-instrumentation-pg-test:
    extends:
      service: base
      file: ./docker-base.yml
    depends_on:
      - postgres
    tmpfs: !reset []
    working_dir: /app/instrumentation/pg/

  ex-instrumentation-net-http:
    extends:
      service: base
      file: ./docker-base.yml
    working_dir: /app/instrumentation/net_http/example

  ex-instrumentation-net-ldap:
    extends:
      service: base
      file: ./docker-base.yml
    working_dir: /app/instrumentation/net_ldap/example

  ex-instrumentation-que:
    extends:
      service: base
      file: ./docker-base.yml
    depends_on:
      - postgres
    working_dir: /app/instrumentation/que

  ex-instrumentation-rack:
    extends:
      service: base
      file: ./docker-base.yml
    working_dir: /app/instrumentation/rack/example

  ex-instrumentation-dalli:
    extends:
      service: base
      file: ./docker-base.yml
    environment:
      - MEMCACHED_URL=memcached:11211
    depends_on:
      - memcached
    working_dir: /app/instrumentation/dalli/example

  ex-instrumentation-restclient:
    extends:
      service: base
      file: ./docker-base.yml
    working_dir: /app/instrumentation/restclient/example

  ex-instrumentation-sinatra:
    extends:
      service: base
      file: ./docker-base.yml
    command: ./start_server.sh
    working_dir: /app/instrumentation/sinatra/example

  jaeger:
    image: jaegertracing/jaeger:2.20.0@sha256:46a886260e04002d8f45e213fc39063fa11a50446048fdaa64786fc0840cb9f8
    ports:
      - "16686:16686"

  otelcol:
    image: otel/opentelemetry-collector:0.156.0@sha256:0beba82d63792511591522a8d582904b9a8ae81710357bfcab731607b8b0ffe2
    command: ["--config=/etc/otelcol-config.yml"]
    volumes:
      - ./otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
