include:
  - ./.docker/volume/bundler.yml
  - ./.docker/infra/kafka/docker-compose.yml
  - ./.docker/infra/memcached/docker-compose.yml
  - ./.docker/infra/mongo/docker-compose.yml
  - ./.docker/infra/mysql/docker-compose.yml
  - ./.docker/infra/postgres/docker-compose.yml
  - ./.docker/infra/rabbitmq/docker-compose.yml
  - ./.docker/infra/redis/docker-compose.yml

services:
  app:
    extends:
      service: base
      file: ./docker-base.yml
    build:
      context: .
    working_dir: /app
    environment:
      - MEMCACHED_URL=memcached:11211
      - TEST_MYSQL_USER=root
      - TEST_MYSQL_ROOT_PASSWORD=root
      - TEST_MYSQL_HOST=mysql
      - TEST_MYSQL_PORT=3306
      - TEST_MYSQ_DB=mysql
      - TEST_POSTGRES_PASSWORD=postgres
      - TEST_POSTGRES_USER=postgres
      - TEST_POSTGRES_HOST=postgres
      - TEST_POSTGRES_PORT=5432
      - TEST_POSTGRES_DB=postgres
    depends_on:
      - kafka
      - jaeger
      - mysql
      - mongo
      - memcached
      - otelcol
      - postgres
      - rabbitmq
      - redis

  ex-instrumentation-mysql2-test:
    extends:
      service: base
      file: ./docker-base.yml
    environment:
      - TEST_MYSQL_USER=root
      - TEST_MYSQL_ROOT_PASSWORD=root
      - TEST_MYSQL_HOST=mysql
      - TEST_MYSQL_PORT=3306
      - TEST_MYSQ_DB=mysql
    depends_on:
      - mysql
    working_dir: /app/instrumentation/mysql2/

  ex-instrumentation-pg-test:
    extends:
      service: base
      file: ./docker-base.yml
    environment:
      - TEST_POSTGRES_PASSWORD=postgres
      - TEST_POSTGRES_USER=postgres
      - TEST_POSTGRES_HOST=postgres
      - TEST_POSTGRES_PORT=5432
      - TEST_POSTGRES_DB=postgres
    depends_on:
      - postgres
    tmpfs: !reset []
    working_dir: /app/instrumentation/pg/

  ex-instrumentation-que-test:
    extends:
      service: base
      file: ./docker-base.yml
    environment:
      - TEST_POSTGRES_PASSWORD=postgres
      - TEST_POSTGRES_USER=postgres
      - TEST_POSTGRES_HOST=postgres
      - TEST_POSTGRES_PORT=5432
      - TEST_POSTGRES_DB=postgres
    depends_on:
      - postgres
    working_dir: /app/instrumentation/que

  jaeger:
    image: jaegertracing/jaeger:2.18.0@sha256:d2cbd047e44b50c11454820f84fd5f34c24a435e5301cf94fe026bf055db80b3
    ports:
      - "16686:16686"

  otelcol:
    image: otel/opentelemetry-collector:0.153.0@sha256:6ed874ea083d67a3085acfc75343f2ad11d9abe6006d7ea4a16e2dba9af14e49
    command: ["--config=/etc/otelcol-config.yml"]
    volumes:
      - ./otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
