include:
  - ./.docker/volume/bundler.yml
  - ./.docker/infra/kafka/docker-compose.yml
  - ./.docker/infra/memcached/docker-compose.yml
  - ./.docker/infra/mongo/docker-compose.yml
  - ./.docker/infra/mysql/docker-compose.yml
  - ./.docker/infra/postgres/docker-compose.yml
  - ./.docker/infra/rabbitmq/docker-compose.yml
  - ./.docker/infra/redis/docker-compose.yml

services:
  app:
    extends:
      service: base
      file: ./docker-base.yml
    build:
      context: .
    working_dir: /app
    environment:
      - MEMCACHED_URL=memcached:11211
      - TEST_MYSQL_USER=root
      - TEST_MYSQL_ROOT_PASSWORD=root
      - TEST_MYSQL_HOST=mysql
      - TEST_MYSQL_PORT=3306
      - TEST_MYSQ_DB=mysql
      - TEST_POSTGRES_PASSWORD=postgres
      - TEST_POSTGRES_USER=postgres
      - TEST_POSTGRES_HOST=postgres
      - TEST_POSTGRES_PORT=5432
      - TEST_POSTGRES_DB=postgres
    depends_on:
      - kafka
      - jaeger
      - mysql
      - mongo
      - memcached
      - otelcol
      - postgres
      - rabbitmq
      - redis

  ex-instrumentation-mysql2-test:
    extends:
      service: base
      file: ./docker-base.yml
    environment:
      - TEST_MYSQL_USER=root
      - TEST_MYSQL_ROOT_PASSWORD=root
      - TEST_MYSQL_HOST=mysql
      - TEST_MYSQL_PORT=3306
      - TEST_MYSQ_DB=mysql
    depends_on:
      - mysql
    working_dir: /app/instrumentation/mysql2/

  ex-instrumentation-pg-test:
    extends:
      service: base
      file: ./docker-base.yml
    environment:
      - TEST_POSTGRES_PASSWORD=postgres
      - TEST_POSTGRES_USER=postgres
      - TEST_POSTGRES_HOST=postgres
      - TEST_POSTGRES_PORT=5432
      - TEST_POSTGRES_DB=postgres
    depends_on:
      - postgres
    tmpfs: !reset []
    working_dir: /app/instrumentation/pg/

  ex-instrumentation-que-test:
    extends:
      service: base
      file: ./docker-base.yml
    environment:
      - TEST_POSTGRES_PASSWORD=postgres
      - TEST_POSTGRES_USER=postgres
      - TEST_POSTGRES_HOST=postgres
      - TEST_POSTGRES_PORT=5432
      - TEST_POSTGRES_DB=postgres
    depends_on:
      - postgres
    working_dir: /app/instrumentation/que

  processor-baggage-test:
    extends:
      service: base
      file: ./docker-base.yml
    working_dir: /app/processor/baggage
    command: |
      bash -c "bundle install && rake"

  jaeger:
    image: jaegertracing/jaeger:2.17.0@sha256:6266573208d665ce5c17483bce0a75d0806480d92c84766d288d0aee885ce708
    ports:
      - "16686:16686"

  otelcol:
    image: otel/opentelemetry-collector:0.150.1@sha256:618f7867e49fdb173d9b46d535b01f82254b0b14beac6ab1f6f2eb8cf62c5d42
    command: ["--config=/etc/otelcol-config.yml"]
    volumes:
      - ./otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
