# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in opentelemetry-metrics-test-helpers.gemspec
gemspec

gem 'rake', '~> 13.0'
gem 'minitest', '~> 5.16'
gem 'opentelemetry-sdk'
gem 'pry-byebug'
