# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[1.0 2.0].each do |version|
  appraise "faraday-#{version}" do
    gem 'faraday', "~> #{version}"
  end
end

appraise 'faraday-latest' do
  gem 'faraday'
end
