include:
   - ./../../../.docker/infra/postgres/docker-compose.yml

services:
  ex-instrumentation-pg:
    extends:
      service: base
      file: ./../../../docker-base.yml
    environment:
      - TEST_POSTGRES_PASSWORD=postgres
      - TEST_POSTGRES_USER=postgres
      - TEST_POSTGRES_HOST=postgres
      - TEST_POSTGRES_PORT=5432
      - TEST_POSTGRES_DB=postgres
      - OTEL_TRACES_EXPORTER=console
    depends_on:
      - postgres
    working_dir: /app/instrumentation/pg/example
