# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[0.10.14 0.10.16].each do |version|
  appraise "active_model_serializers-#{version}" do
    gem 'active_model_serializers', "= #{version}"
    gem 'activesupport', '= 8.1.3.1'
  end
end

%w[7.1.2 8.1.3.1].each do |version|
  appraise "activesupport-#{version}" do
    gem 'activesupport', "= #{version}"
    gem 'benchmark', '= 0.5.0'
    gem 'active_model_serializers', '= 0.10.16'
  end
end
