# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
eval_gemfile File.expand_path('../../Gemfile', __dir__)

gemspec

group :test do
  gem 'active_model_serializers'
  gem 'activesupport'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'logger'
    gem 'mutex_m'
  end

  Dir.entries('../../helpers')
     .select { |entry| File.directory?(File.join('../../helpers', entry)) }
     .reject { |entry| %w[. ..].include?(entry) } # rubocop:disable Performance/CollectionLiteralInLoop
     .sort
     .each { |dir| gem "opentelemetry-helpers-#{dir}", path: "../../helpers/#{dir}" }

  excluded_instrumentations = %w[. .. all logger]
  Dir.entries('../')
     .select { |entry| File.directory?(File.join('../', entry)) }
     .reject { |entry| excluded_instrumentations.include?(entry) }
     .sort
     .each { |dir| gem "opentelemetry-instrumentation-#{dir}", path: "../#{dir}" }
end
