inherit_from: ../../.rubocop.yml

Metrics/ParameterLists:
  Enabled: true
  Exclude:
    - lib/opentelemetry/instrumentation/ruby_kafka/patches/client.rb
    - lib/opentelemetry/instrumentation/ruby_kafka/patches/producer.rb
