AllCops:
  DisabledByDefault: true

Lint/Syntax:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - lib/opentelemetry/instrumentation/ruby_kafka/patches/client.rb
    - lib/opentelemetry/instrumentation/ruby_kafka/patches/producer.rb
