# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

(3..5).each do |i|
  appraise "ruby-kafka-1.#{i}.x" do
    gem 'ruby-kafka', "~> 1.#{i}.0"
  end
end
