# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[1.4.0 1.5.0].each do |version|
  appraise "ruby-kafka-#{version}" do
    gem 'ruby-kafka', "= #{version}"
  end
end
