# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[0.6.1 0.8.1].each do |version|
  appraise "lmdb-#{version}" do
    gem 'lmdb', "~> #{version}"
  end
end