# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/base/*.gemspec'
  gem 'opentelemetry-helpers-sql', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'helpers/sql/*.gemspec'
  gem 'opentelemetry-helpers-mysql', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'helpers/mysql/*.gemspec'
  gem 'opentelemetry-helpers-sql-processor', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'helpers/sql-processor/*.gemspec'
  gem 'appraisal', '~> 2.5'
  gem 'minitest', '~> 5.0'
  gem 'opentelemetry-sdk', '~> 1.1'
  gem 'opentelemetry-test-helpers', '~> 0.3'
  gem 'rubocop', '~> 1.82.0'
  gem 'rubocop-performance', '~> 1.26.0'
  gem 'simplecov', '~> 0.22.0'
  gem 'yard', '~> 0.9'

  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'bigdecimal'
    gem 'mutex_m'
  end
end
