# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
eval_gemfile File.expand_path('../../Gemfile', __dir__)

gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'opentelemetry-helpers-sql', path: '../../helpers/sql'
  gem 'opentelemetry-helpers-mysql', path: '../../helpers/mysql'
  gem 'opentelemetry-helpers-sql-processor', path: '../../helpers/sql-processor'
  gem 'dotenv', '~> 3.2.0'
  gem 'opentelemetry-sdk', '~> 1.13.0'
  gem 'opentelemetry-test-helpers', '~> 0.9.0'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'bigdecimal'
    gem 'logger'
    gem 'mutex_m'
  end
end
