# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source "https://rubygems.org"

gem "opentelemetry-api"
gem "opentelemetry-common"
gem "opentelemetry-instrumentation-gruf", path: "../../gruf"
gem "opentelemetry-sdk"
gem "gruf"
gem "google-protobuf"
