# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'minitest', '~> 6.0.0'
  gem 'opentelemetry-sdk', '~> 1.12.0'
  gem 'opentelemetry-test-helpers', '~> 0.9.0'
  gem 'rake', '>= 13'
  gem 'rubocop', '~> 1.88.0'
  gem 'rubocop-performance', '~> 1.26.0'
  gem 'simplecov', '~> 1.0.0'
  gem 'yard', '~> 0.9.0'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'logger'
    gem 'mutex_m'
  end
end
