# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

## TODO: Include the supported version to be tested here.
## Example:
# %w[2.0.0 2.1.2].each do |version|
#   appraise "rack-#{version}" do
#     gem 'rack', "~> #{version}"
#   end
# end