# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

# DO NOT ADD DEPENDENCIES HERE!
# Please declare a minimum development dependency in the gemspec,
# then target specific versions in the Appraisals file.

gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'appraisal', '~> 2.5'
  gem 'bundler', '~> 2.4'
  gem 'minitest', '~> 5.0'
  gem 'opentelemetry-sdk', '~> 1.0'
  gem 'opentelemetry-test-helpers', '~> 0.3'
  gem 'rake', '~> 13.0'
  gem 'rubocop', '~> 1.70.0'
  gem 'rubocop-performance', '~> 1.19.1'
  gem 'simplecov', '~> 0.17.1'
  gem 'webmock', '~> 3.24'
  gem 'yard', '~> 0.9'
end
