# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'que-1.2' do
  gem 'que', '1.2.0'
end

appraise 'que-2.1' do
  ruby '>= 2.7'
  gem 'que', '2.1.0'
end
