# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'que-1.x' do
  gem 'que', '~> 1.4'
end

appraise 'que-2.x' do
  gem 'que', '~> 2.3'
end

appraise 'que-latest' do
  gem 'que'
end
