# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'que-2.x' do
  gem 'que', '~> 2.4'
  gem 'activerecord', '~> 7.2'
  gem 'pg', '~> 1.5'
end

appraise 'que-latest' do
  gem 'que'
  gem 'activerecord'
  gem 'pg'
end
