include:
  - ../../.docker/devcontainer/alpine/compose.yml
  - ../../.docker/infra/postgres/docker-compose.yml
  - ../../.docker/volume/bundler.yml

services:
  ex-instrumentation-pg-test:
    extends:
      service: devcontainer-alpine
      file: ../../.docker/devcontainer/alpine/compose.yml
    environment:
      - TEST_POSTGRES_HOST=postgres
    depends_on:
      - postgres
    working_dir: /app/instrumentation/que/
