# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'activerecord', '< 7.2.0', '> 7.0.0'
  gem 'pg'
  gem 'opentelemetry-helpers-sql', path: '../../helpers/sql'
  gem 'opentelemetry-helpers-sql-obfuscation', path: '../../helpers/sql-obfuscation'
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'opentelemetry-instrumentation-pg', path: '../pg'
end
