# frozen_string_literal: true

if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('3.2.0')
  appraise 'sidekiq-latest' do
    gem 'sidekiq'
  end

  appraise 'sidekiq-8.0' do
    gem 'sidekiq', '~> 8.0'
  end
end

appraise 'sidekiq-7.3' do
  gem 'sidekiq', '~> 7.3'
end
