# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[0.66.0 0.80.0].each do |version|
  appraise "openai-#{version}" do
    gem 'openai', "~> #{version}"
  end

  # Logs support is opt-in, based on the presence of the
  # opentelemetry-logs-api and opentelemetry-logs-sdk gems.
  # This Appraisal tests behavior with them present.
  appraise "openai-#{version}-logs" do
    gem 'openai', "~> #{version}"
    gem 'opentelemetry-logs-api', '= 0.4.1'
    gem 'opentelemetry-logs-sdk', '= 0.6.1'
  end
end
