# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[0.66.0 0.80.0].each do |version|
  appraise "openai-#{version}" do
    gem 'openai', "~> #{version}"
end
