# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'appraisal', '~> 2.5.0'
  gem 'minitest', '~> 6.0.6'
  gem 'opentelemetry-sdk', '~> 1.12.0'
  gem 'opentelemetry-test-helpers', '~> 0.9.0'
  gem 'rake', '~> 13.4.2'
  gem 'rubocop', '~> 1.90.0'
  gem 'rubocop-minitest', '~> 0.40.0'
  gem 'rubocop-rspec', '~> 3.10.2'
  gem 'rubocop-rake', '~> 0.7.1'
  gem 'rubocop-performance', '~> 1.27.0'
  gem 'simplecov', '~> 1.1.0'
  gem 'webmock', '~> 3.26.2'
  gem 'yard', '~> 0.9.44'
  if RUBY_VERSION >= '3.4'
    gem 'base64', '~> 0.3.0'
    gem 'mutex_m', '~> 0.3.0'
    gem 'logger', '~> 1.7.0'
    gem 'cgi', '~> 0.5.1'
  end
end
