# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
eval_gemfile File.expand_path('../../Gemfile', __dir__)

gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'opentelemetry-sdk', '~> 1.12.0'
  gem 'opentelemetry-logs-sdk', '~> 0.6.0'
  gem 'opentelemetry-test-helpers', '~> 0.9.0'
  gem 'webmock', '~> 3.26.2'
  if RUBY_VERSION >= '3.4'
    gem 'base64', '~> 0.3.0'
    gem 'mutex_m', '~> 0.3.0'
    gem 'logger', '~> 1.7.0'
    gem 'cgi', '~> 0.5.1'
  end
end
