# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-sdk-core'
gem 'aws-sdk-sns'
gem 'opentelemetry-api'
gem 'opentelemetry-instrumentation-aws_sdk'
gem 'opentelemetry-sdk'
# AWS SDK core needs an XML library
gem 'rexml'
