# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in opentelemetry-propagator-ottrace.gemspec
gemspec

group :test do
  gem 'appraisal', '~> 2.5.0'
  gem 'minitest', '~> 6.0.0'
  gem 'rake', '>= 13'
  gem 'rubocop', '~> 1.90.0'
  gem 'rubocop-performance', '~> 1.27.0'
  gem 'simplecov', '~> 1.1.0'
  gem 'yard', '~> 0.9.0'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'logger'
    gem 'mutex_m'
  end
end
