include:
  - ./../../../.docker/infra/rabbitmq/docker-compose.yml

services:
  ex-instrumentation-bunny:
    extends:
      service: base
      file: ./../../../docker-base.yml
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    working_dir: /app/instrumentation/bunny/example
