# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[0.12.0 0.13.0 0.14.0].each do |version|
  appraise "rdkafka-#{version}" do
    gem 'rdkafka', "~> #{version}"
  end
end

appraise 'rdkafka-latest' do
  gem 'rdkafka'
end
