# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[0.18.0 0.29.1].each do |version|
  appraise "rdkafka-#{version}" do
    gem 'rdkafka', "~> #{version}"
  end
end
