# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/example_api.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('example/example_api.proto', syntax: :proto3) do
    add_message 'proto.example.ExampleRequest' do
      optional :id, :uint64, 1
      optional :name, :string, 2
    end
    add_message 'proto.example.ExampleResponse' do
      optional :response_name, :string, 1
    end
  end
end

module Proto
  module Example
    ExampleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('proto.example.ExampleRequest').msgclass
    ExampleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('proto.example.ExampleResponse').msgclass
  end
end
