# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in opentelemetry-propragator-google_cloud_platform.gemspec
gemspec

group :test do
  if RUBY_VERSION >= '3.4'
    gem 'mutex_m'
  end
end
