# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :development do
  gem 'appraisal', '~> 2.5.0'
  gem 'rake', '>= 13'
  gem 'rubocop', '~> 1.90.0'
  gem 'rubocop-performance', '~> 1.26.0'
  gem 'rubocop-rake', '~> 0.7.1'
  gem 'rubocop-rspec', '~> 3.10.2'
  gem 'rubocop-minitest', '~> 0.40.0'
  gem 'simplecov', '~> 1.2.0'
  gem 'yard', '~> 0.9.0'
end

group :test do
  gem 'minitest', '~> 6.0.0'
  gem 'rspec-mocks', '~> 3.13.7'
  gem 'webmock', '~> 3.26.0'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'logger'
    gem 'mutex_m'
  end
end
