# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[1.76.0 1.83.0].each do |version|
  appraise "grpc-#{version}" do
    gem 'grpc', "= #{version}", platform: :mri
  end
end
