# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

# Specify your gem's dependencies in opentelemetry-instrumentation-grpc.gemspec
gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'pry'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'mutex_m'
  end
end
