# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

# Specify your gem's dependencies in opentelemetry-instrumentation-grpc.gemspec
gemspec

group :test do
  gem 'appraisal', '~> 2.5'
  gem 'bundler', '~> 2.4'
  gem 'google-protobuf', '~> 4.29'
  gem 'grpc-tools', '~> 1.64'
  gem 'minitest', '~> 5.0'
  gem 'opentelemetry-sdk', '~> 1.1'
  gem 'opentelemetry-test-helpers', '~> 0.4'
  gem 'rake', '~> 13.2'
  gem 'rubocop', '~> 1.81.1'
  gem 'rubocop-performance', '~> 1.26.0'
  gem 'simplecov', '~> 0.22.0'
  gem 'yard', '~> 0.9'
  gem 'opentelemetry-instrumentation-base', path: '../base'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'mutex_m'
  end
end
