# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

# To faclitate HTTP semantic convention stability migration, we are using
# appraisal to test the different semantic convention modes along with different
# HTTP gem versions. For more information on the semantic convention modes, see:
# https://opentelemetry.io/docs/specs/semconv/non-normative/http-migration/

semconv_stability = %w[stable old dup]

# https://github.com/rack/rack/tree/main?tab=readme-ov-file#version-support
semconv_stability.each do |mode|
  appraise "rack-latest-#{mode}" do
    gem 'rack'
  end

  appraise "rack-3.1-#{mode}" do
    gem 'rack', '~> 3.1.0'
  end

  next unless Gem::Version.new(RUBY_VERSION) < Gem::Version.new('4')

  appraise "rack-2.2.x-#{mode}" do
    gem 'rack', '~> 2.2.0'
  end
end
