# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'opentelemetry-metrics-sdk', '~> 0.11'
  gem 'rake', '~> 13.4.0'
  gem 'rubocop', '~> 1.87.0'
  gem 'appraisal', '~> 2.5.0'
  gem 'minitest', '~> 6.0.0'
  gem 'opentelemetry-sdk', '~> 1.12.0'
  gem 'opentelemetry-sdk-experimental', '~> 0.6.0'
  gem 'opentelemetry-test-helpers', '~> 0.9.0'
  gem 'rubocop-performance', '~> 1.26.0'
  gem 'rubocop-minitest', '~> 0.39.1'
  gem 'rubocop-rspec', '~> 3.10', '>= 3.10.2'
  gem 'rubocop-rake', '~> 0.7.1'
  gem 'simplecov', '~> 0.22.0'
  gem 'webmock', '~> 3.26.0'
  gem 'yard', '~> 0.9.0'
  gem 'rspec-mocks', '~> 3.13.7'
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'rack-test', '~> 2.2.0'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'logger'
    gem 'mutex_m'
  end
end
