# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

if RUBY_ENGINE == 'ruby'
  %w[7.1.0 7.2.0].each do |version|
    appraise "activestorage-#{version}" do
      gem 'sqlite3', '< 2.0.0', platform: :mri
      gem 'image_processing', '= 2.0.3'
      gem 'mini_magick', '= 5.3.3'
      gem 'image_processing', '= 1.14.0'
      gem 'rails', "~> #{version}"
    end
  end

  %w[8.0.0 8.1.0].each do |version|
    appraise "activestorage-#{version}" do
      gem 'rails', "~> #{version}"
      gem 'sqlite3', '= 2.9.6'
      gem 'image_processing', '= 2.0.3'
      gem 'mini_magick', '= 5.3.3'
    end
  end
end

if RUBY_ENGINE == 'jruby'
  %w[71.0 72.0 80.0.pre1].each do |version|
    appraise "jruby_activestorage-#{version}" do
      gem 'activerecord-jdbcsqlite3-adapter', "~> #{version}"
      gem 'image_processing', '= 2.0.3'
      gem 'mini_magick', '= 5.3.3'
      gem 'rails'
    end
  end
end
