# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
%w[3.7.0 3.7.0].each do |version|
  appraise "koala-#{version}" do
    gem 'koala', "~> #{version}"
    gem 'json', '< 3'
  end
end
