include:
  - ./../../../.docker/infra/memcached/docker-compose.yml

services:
  ex-instrumentation-dalli:
    extends:
      service: base
      file: ./../../../docker-base.yml
    depends_on:
      - memcached
    working_dir: /app/instrumentation/dalli/example
