inherit_from: ../.rubocop-examples.yml

Naming/FileName:
  Exclude:
    - "lib/opentelemetry-instrumentation-dalli.rb"
Naming/MethodParameterName:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
