services:
  mysql:
    image: mysql:8.4.0@sha256:dab7049abafe3a0e12cbe5e49050cf149881c0cd9665c289e5808b9dad39c9e0
    command: mysqld --mysql-native-password=ON
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=mysql
      - MYSQL_USER=mysql
    volumes:
      - init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
