# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'grape-1.x' do
  gem 'rack', '~> 2.0'
  gem 'grape', '~> 1.8'
end

appraise 'grape-2.0.x' do
  gem 'grape', '~> 2.0.0'
end

appraise 'grape-latest' do
  gem 'grape'
end
