# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'racecar-2.7' do
  gem 'racecar', '~> 2.7.0'
end

appraise 'racecar-2.8' do
  gem 'racecar', '~> 2.8.2'
end

appraise 'racecar-2.10' do
  gem 'racecar', '~> 2.10'
end

appraise 'racecar-2.12' do
  gem 'racecar', '~> 2.12'
end
