services:
  postgres:
    image: postgres:14.24@sha256:816cf7d06ec33116c8f54cf14197085be89f25291686229485ee7d53a785b901
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 2s
      retries: 3
    volumes:
      - /var/run/postgresql:/var/run/postgresql
