# frozen_string_literal: true

# add more tests for excon

%w[0.71 0.109].each do |version|
  appraise "excon-#{version}" do
    gem 'excon', "~> #{version}.0"
  end
end

appraise 'excon-latest' do
  gem 'excon'
end
