# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/support/proto/ping.proto

require 'google/protobuf'


descriptor_data = "\n\x1dtest/support/proto/ping.proto\x12\rsupport.proto\"0\n\x0bPingRequest\x12\r\n\x05value\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\r\"\x1d\n\x0cPingResponse\x12\r\n\x05value\x18\x01 \x01(\t2\xd7\x02\n\nPingServer\x12P\n\x13RequestResponsePing\x12\x1a.support.proto.PingRequest\x1a\x1b.support.proto.PingResponse\"\x00\x12Q\n\x12\x43lientStreamerPing\x12\x1a.support.proto.PingRequest\x1a\x1b.support.proto.PingResponse\"\x00(\x01\x12Q\n\x12ServerStreamerPing\x12\x1a.support.proto.PingRequest\x1a\x1b.support.proto.PingResponse\"\x00\x30\x01\x12Q\n\x10\x42idiStreamerPing\x12\x1a.support.proto.PingRequest\x1a\x1b.support.proto.PingResponse\"\x00(\x01\x30\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Support
  module Proto
    PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("support.proto.PingRequest").msgclass
    PingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("support.proto.PingResponse").msgclass
  end
end
