# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: test/support/proto/ping.proto for package 'support.proto'

require_relative 'ping_pb'

module Support
  module Proto
    module PingServer
      class Service
        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'support.proto.PingServer'

        rpc :RequestResponsePing, ::Support::Proto::PingRequest, ::Support::Proto::PingResponse
        rpc :ClientStreamerPing, stream(::Support::Proto::PingRequest), ::Support::Proto::PingResponse
        rpc :ServerStreamerPing, ::Support::Proto::PingRequest, stream(::Support::Proto::PingResponse)
        rpc :BidiStreamerPing, stream(::Support::Proto::PingRequest), stream(::Support::Proto::PingResponse)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
