# frozen_string_literal: true

# To facilitate HTTP semantic convention stability migration, we are using
# appraisal to test the different semantic convention modes along with different
# gem versions. For more information on the semantic convention modes, see:
# https://opentelemetry.io/docs/specs/semconv/non-normative/http-migration/

semconv_stability = %w[dup stable old]

semconv_stability.each do |mode|
  appraise "rest-client-latest_#{mode}" do
    gem 'rest-client'
  end
end
