# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[6.1.0 7.0.0 7.1.0 7.2.0].each do |version|
  appraise "action_view-#{version}" do
    gem 'rails', "~> #{version}"
  end
end

appraise 'action_view-latest' do
  gem 'action_view'
end
