# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'opentelemetry-instrumentation-active_support', path: '../active_support'
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'nokogiri', platforms: [:ruby, :x64_mingw]
  gem 'pry-byebug'
  gem 'sqlite3', platforms: [:ruby, :x64_mingw]
end
