# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gem 'activesupport'
gem 'opentelemetry-instrumentation-base', path: '../../base'
gem 'opentelemetry-instrumentation-racecar', path: '../'
gem 'opentelemetry-sdk'
gem 'racecar'
