# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-api'
gem 'opentelemetry-common'
gem 'opentelemetry-instrumentation-rack', path: '../'
gem 'opentelemetry-sdk'
gem 'opentelemetry-sdk-experimental', git: 'https://github.com/open-telemetry/opentelemetry-ruby.git', glob: 'sdk_experimental/*.gemspec', branch: 'main'
gem 'rack'
gem 'rack-test'
gem 'pry'
