# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'activejob-6.1' do
  gem 'activejob', '~> 6.1.0'
end

appraise 'activejob-6.0' do
  gem 'activejob', '~> 6.0.0'
end

if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.7.0')
  appraise 'rails-7.0' do
    gem 'rails', '~> 7.0.0'
  end
end
