# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gem 'nokogiri', force_ruby_platform: true

gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', path: '../base'
end
