# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'activesupport-6.1' do
  gem 'activesupport', '~> 6.1.0'
end

appraise 'activesupport-7.0' do
  gem 'activesupport', '~> 7.0.0'
end

appraise 'activesupport-7.1' do
  gem 'activesupport', '~> 7.1.0'
end

if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('3.1.0')
  appraise 'activesupport-7.2' do
    gem 'activesupport', '~> 7.2.0'
  end
end
