# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'appraisal2', '~> 3.2.2'
  gem 'minitest', '~> 6.0.0'
  gem 'opentelemetry-test-helpers', '~> 0.9.0'
  gem 'rake', '>= 13'
  gem 'rubocop', '~> 1.90.0'
  gem 'rubocop-performance', '~> 1.27.0'
  gem 'simplecov', '~> 1.1.0'
  gem 'webmock', '~> 3.26.0'
  gem 'yard', '~> 0.9.0'
  gem 'opentelemetry-sdk', '~> 1.13.0'
  gem 'rspec-mocks', '~> 3.13.7'
  gem 'opentelemetry-instrumentation-base', path: '../base'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'mutex_m'
    gem 'logger'
  end
end
