# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

# Max compatible version of 2.0.x

(0..4).each do |minor_version|
  appraise "graphql-2.#{minor_version}.x" do
    gem 'graphql', "~> 2.#{minor_version}.0"
  end
end

appraise 'graphql-c_parser-1.0.x' do
  gem 'graphql', '< 2.3.1'
  gem 'graphql-c_parser', '~> 1.0.0', platform: :mri
end

appraise 'graphql-c_parser-1.x' do
  gem 'graphql-c_parser', '~> 1.1', platform: :mri
  gem 'graphql', platform: :jruby
end

appraise 'graphql-c_parser-latest' do
  gem 'graphql-c_parser', platform: :mri
  gem 'graphql', platform: :jruby
end

appraise 'graphql-latest' do
  gem 'graphql'
end
