# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

# Max compatible version of 2.0.x

(0..4).each do |minor_version|
  appraise "graphql-2.#{minor_version}.x" do
    gem 'graphql', "~> 2.#{minor_version}.0"
  end
end

(0..1).each do |minor_version|
  gem 'graphql-c_parser', "~> 1.#{minor_version}.0"
end

appraise 'graphql-c_parser-latest' do
  gem 'graphql-c_parser'
end

appraise 'graphql-latest' do
  gem 'graphql'
end
