# frozen_string_literal: true

appraise 'base' do # rubocop: disable Lint/EmptyBlock
end

appraise 'metrics-api' do
  gem 'opentelemetry-metrics-api'
end

appraise 'metrics-sdk' do
  gem 'opentelemetry-sdk'
  gem 'opentelemetry-metrics-sdk'
end
