# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gem 'opentelemetry-metrics-api', '~> 0.2'
gem 'opentelemetry-metrics-sdk'

gemspec
