# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gem 'opentelemetry-test-helpers', github: 'zvkemp/opentelemetry-ruby', ref: 'test-helpers-metrics'

gemspec

group :test do
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'mutex_m'
  end
end
