# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[0.10.10 0.10.16].each do |version|
  appraise "active_model_serializers-#{version}" do
    gem 'active_model_serializers', "= #{version}"
  end
end
