# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
eval_gemfile File.expand_path('../../Gemfile', __dir__)

gemspec

group :test do
  gem 'opentelemetry-sdk', '~> 1.13.0'
  gem 'opentelemetry-test-helpers', '~> 0.9.0'
  gem 'webmock', '~> 3.26.0'
  gem 'rspec-mocks', '~> 3.13.7'
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'opentelemetry-instrumentation-active_support', path: '../active_support'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'mutex_m'
    gem 'logger'
  end
end
