include:
  - ./../../../.docker/infra/mysql/docker-compose.yml

services:
  ex-instrumentation-mysql2:
    extends:
      service: base
      file: ./../../../docker-base.yml
    depends_on:
      - mysql
    working_dir: /app/instrumentation/mysql2/example
