# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dotenv'
gem 'mysql2'
gem 'opentelemetry-api'
gem 'opentelemetry-common'
gem 'opentelemetry-instrumentation-mysql2'
gem 'opentelemetry-sdk'
