# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in opentelemetry-propagator-vitess.gemspec
gemspec

group :test do
  gem 'minitest', '~> 6.0'
  gem 'rake', '>= 13'
  gem 'rubocop', '~> 1.84.0'
  gem 'rubocop-performance', '~> 1.26.0'
  gem 'simplecov', '~> 0.22.0'
  gem 'yard', '~> 0.9'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'logger'
    gem 'mutex_m'
  end
end
