# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'minitest', '~> 5.0'
  gem 'simplecov', '~> 0.17.1'
  gem 'webmock', '~> 3.7.0'
end

group :development do
  gem 'rubocop', '~> 1.42.0'
  gem 'yard', '~> 0.9'
end
