# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'trilogy-2.9' do
  gem 'trilogy', '~> 2.9.0'
end

appraise 'trilogy-latest' do
  gem 'trilogy'
end
