# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'opentelemetry-helpers-mysql', path: '../../helpers/mysql'
  gem 'opentelemetry-helpers-sql', path: '../../helpers/sql'
  gem 'opentelemetry-helpers-sql-obfuscation', path: '../../helpers/sql-obfuscation'
  gem 'opentelemetry-propagator-vitess', path: '../../propagator/vitess'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'mutex_m'
  end
end
