# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'bundler', '~> 2.4'
  gem 'minitest', '~> 5.0'
  gem 'opentelemetry-test-helpers', '~> 0.3'
  gem 'rake', '~> 13.0'
  gem 'rubocop', '~> 1.79.1'
  gem 'rubocop-performance', '~> 1.25.0'
  gem 'simplecov', '~> 0.22.0'
  gem 'yard', '~> 0.9'
  gem 'yard-doctest', '~> 0.1.6'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'mutex_m'
  end
end
