# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test do
  gem 'byebug'
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'pry-byebug'
  gem 'sqlite3', '~> 1.4'
end
