# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-api'
gem 'opentelemetry-common'
gem 'opentelemetry-instrumentation-gruf', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/../gruf/*.gemspec'
gem 'opentelemetry-sdk'
gem 'gruf'
gem 'google-protobuf'
