# frozen_string_literal: true

%w[1.1.0 1.2.0 1.3.0].each do |version|
  appraise "concurrent-ruby-#{version}" do
    gem 'concurrent-ruby', "~> #{version}"
  end
end

appraise 'concurrent-ruby-latest' do
  gem 'concurrent-ruby'
end
