# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'httpx-1' do
  gem 'httpx', '~> 1.0'
end

appraise 'httpx-0' do
  gem 'httpx', '~> 0.24'
end
