# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
eval_gemfile File.expand_path('../../Gemfile', __dir__)

gemspec

group :test do
  gem 'opentelemetry-test-helpers', '~> 0.8.0'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'mutex_m'
    gem 'logger'
  end
end
