# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'mongo-latest' do
  gem 'mongo'

  # TODO: bson 5.1.0 isn't compatible with JRuby as of 2025/06/17
  gem 'bson', '< 5.1.0' if defined?(JRUBY_VERSION)
end
