# frozen_string_literal: true

source 'https://rubygems.org'
eval_gemfile File.expand_path('../../Gemfile', __dir__)

# Specify your gem's dependencies in opentelemetry-processor-baggage.gemspec
gemspec

group :test do
  gem 'opentelemetry-sdk', '~> 1.13.0'
  gem 'rspec-mocks', '~> 3.13.7'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'logger'
    gem 'mutex_m'
  end
end
