services:
  redis:
    image: redis:8.8.0@sha256:234c902a2db49461a129e2d4aeff85b28cf20187ed274a67f6e50995fa713c7b
    environment:
      REDIS_PASSWORD: passw0rd
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "passw0rd"]
    healthcheck:
      test: ["CMD-SHELL", 'redis-cli -a "passw0rd" ping']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

volumes:
  redis_data:
