services:
  redis:
    image: redis:8.10.2@sha256:2c2dff791878316e3b083188be0d578423b24813cdda5de0e80ea4f7b3e6bfd6
    environment:
      REDIS_PASSWORD: passw0rd
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "passw0rd"]
    healthcheck:
      test: ["CMD-SHELL", 'redis-cli -a "passw0rd" ping']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

volumes:
  redis_data:
