# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport'
gem 'opentelemetry-api'
gem 'opentelemetry-common'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-ruby_kafka', git: 'https://github.com/open-telemetry/opentelemetry-ruby-contrib.git', branch: 'main', glob: 'instrumentation/ruby_kafka/*.gemspec'
gem 'opentelemetry-sdk'
gem 'ruby-kafka'
