include:
  - ./../../../.docker/infra/postgres/docker-compose.yml

services:
  ex-instrumentation-que:
    extends:
      service: base
      file: ./../../../docker-base.yml
    depends_on:
      - postgres
    working_dir: /app/instrumentation/que/example
