# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

# DO NOT ADD DEPENDENCIES HERE!
# Please declare a minimum development dependency in the gemspec,
# then target specific versions in the Appraisals file.

gemspec

group :test do
  gem 'appraisal', '~> 2.5.0'
  gem 'minitest', '~> 6.0.0'
  gem 'rspec-mocks', '~> 3.13.7'
  gem 'opentelemetry-sdk', '~> 1.11.0'
  gem 'opentelemetry-logs-sdk', '~> 0.5.0'
  gem 'opentelemetry-test-helpers', '~> 0.8.0'
  gem 'rubocop', '~> 1.86.0'
  gem 'rubocop-performance', '~> 1.26.0'
  gem 'simplecov', '~> 0.22.0'
  gem 'webmock', '~> 3.26.0'
  gem 'yard', '~> 0.9.0'
  gem 'opentelemetry-instrumentation-base', path: '../base'
  if RUBY_VERSION >= '3.4'
    gem 'base64'
    gem 'mutex_m'
    gem 'logger'
  end
end
