# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

# DO NOT ADD DEPENDENCIES HERE!
# Please declare a minimum development dependency in the gemspec,
# then target specific versions in the Appraisals file.

gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'opentelemetry-api', path: '/Users/kreopelle/dev/opentelemetry-ruby/api'
  gem 'opentelemetry-logs-api', path: '/Users/kreopelle/dev/opentelemetry-ruby/logs_api'
  gem 'opentelemetry-logs-sdk', path: '/Users/kreopelle/dev/opentelemetry-ruby/logs_sdk'
  gem 'opentelemetry-sdk', path: '/Users/kreopelle/dev/opentelemetry-ruby/sdk'
end
