# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

%w[6.1.0 7.0.0 7.1.0].each do |version|
  appraise "rails-#{version}" do
    gem 'rails', "~> #{version}"
  end
end

if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('3.1.0')
  %w[7.2.0].each do |version|
    appraise "rails-#{version}" do
      gem 'rails', "~> #{version}"
    end
  end

  appraise 'rails-latest' do
    gem 'rails'
  end
end
