# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

# To facilitate HTTP semantic convention stability migration, we are using
# appraisal to test the different semantic convention modes/ Rack middlewares.
# When the migration is complete, we should revert testing with different stability
# modes. For more information see CHANGELOG: HTTP semantic convention stability
semconv_stability = %w[dup stable old]

sinatra_versions = %w[]
sinatra_versions.push('3.2.0', '2.2.0') if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('4')

semconv_stability.each do |mode|
  %w[4.0.0 4.1.0 4.2.0].each do |version|
    appraise "sinatra-#{version}-#{mode}" do
      gem 'sinatra', "= #{version}"
    end
  end

  sinatra_versions.each do |version|
    appraise "sinatra-#{version}-#{mode}" do
      gem 'sinatra', "= #{version}"
    end
  end
end
