# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

# To facilitate HTTP semantic convention stability migration, we are using
# appraisal to test the different semantic convention modes/ Rack middlewares.
# When the migration is complete, we should revert testing with different stability
# modes. For more information see CHANGELOG: HTTP semantic convention stability
semconv_stability = %w[dup stable old]
sinatra_versions = %w[4.1 3.0 2.1]

semconv_stability.each do |mode|
  sinatra_versions.each do |version|
    appraise "sinatra-#{version}-#{mode}" do
      gem 'sinatra', "~> #{version}"
    end
  end

  appraise "sinatra-latest-#{mode}" do
    gem 'sinatra'
  end
end
