# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'factory_bot-4' do
  gem 'factory_bot', '~> 4.0'
  gem 'activesupport', '~> 6.0' # factory_bot 4 requires activesupport < 7 on Ruby 3.4+
end

appraise 'factory_bot-5' do
  gem 'factory_bot', '~> 5.0'
  gem 'activesupport', '~> 6.0' # factory_bot 5 requires activesupport < 7 on Ruby 3.4+
end

%w[6.4.0 6.6.0].each do |version|
  appraise "factory_bot-#{version}" do
    gem 'factory_bot', "~> #{version}"
  end
end
