# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'factory_bot-4.x' do
  gem 'factory_bot', '< 5.0.0'
  gem 'activesupport', '< 7.0.0' # factory_bot 4 requires activesupport < 7 on Ruby 3.4+
end

appraise 'factory_bot-5.x' do
  gem 'factory_bot', '< 6.0.0'
  gem 'activesupport', '< 7.0.0' # factory_bot 5 requires activesupport < 7 on Ruby 3.4+
end

%w[6.5.0 6.6.0].each do |version|
  appraise "factory_bot-#{version}" do
    gem 'factory_bot', "~> #{version}"
  end
end
