# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
eval_gemfile File.expand_path('../../Gemfile', __dir__)

gemspec

group :test do
  gem 'opentelemetry-instrumentation-base', path: '../base'
  gem 'opentelemetry-sdk', '~> 1.13.0'
  gem 'opentelemetry-test-helpers', '~> 0.9.0'
  gem 'webmock', '~> 3.26.0'
  if RUBY_VERSION >= '3.4'
    gem 'base64' # Required for activesupport < 7.1 on Ruby 3.4+
    gem 'logger'
    gem 'mutex_m' # Required for activesupport < 7.1 on Ruby 3.4+
    gem 'observer' # Required for factory_bot 4.x on Ruby 3.4+
  end
end
