# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

module OpenTelemetry
  module Instrumentation
    module Grpc
      VERSION: String
      # See the writing guide of rbs: https://github.com/ruby/rbs#guides
    end
  end
end
