name: Local CLI Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - "package.json"
      - "package-lock.json"
      - "Gemfile"
      - "Gemfile.lock"
      - ".github/workflows/ci-checks-local.yml"
  merge_group:

permissions:
  contents: read

jobs:
  runner-checks:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-26
          - windows-2025
    name: All / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: "npm"
          node-version: "24"

      - name: Install Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: "3.3.12"

      - name: Install Chrome (Ubuntu only)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "PUPPETEER_SKIP_DOWNLOAD=true" >> $GITHUB_ENV
          echo "PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome" >> $GITHUB_ENV

      - name: Install Chrome for Testing (macOS/Windows only)
        if: "${{!startsWith(matrix.os, 'ubuntu')}}"
        run: npx puppeteer browsers install chrome

      - name: Install Tools
        run: npm ci --ignore-scripts && npx puppeteer browsers install chrome && bundle install

      - name: Run All Checks
        run: |
          npm run check
        env:
          lsconfig: "-c .github/.linkspector-local_check.yml"

  devcontainer-checks:
    strategy:
      fail-fast: false
    name: All / DevContainer
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build and run dev container task
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          env: |
            lsconfig="-c .github/.linkspector-local_check.yml"
          runCmd: |
            npm ci --ignore-scripts && npx puppeteer browsers install chrome && bundle install
            npm run check
