name: Local CLI Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - "package.json"
      - "package-lock.json"
      - "Gemfile"
      - "Gemfile.lock"
      - ".github/workflows/ci-checks-local.yml"
  merge_group:

permissions:
  contents: read

jobs:
  automated-checks:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
          - windows-2025
    name: All / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      lsConfig: '-c .github/linkspector-local_check.yml'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: "npm"
          node-version: "24"

      - name: Install Ruby
        uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
        with:
          ruby-version: "3.3.11"

      - name: Install Chrome (Ubuntu only)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "PUPPETEER_SKIP_DOWNLOAD=true" >> $GITHUB_ENV
          echo "PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome" >> $GITHUB_ENV

      - name: Install Chrome for Testing (macOS/Windows only)
        if: "${{!startsWith(matrix.os, 'ubuntu')}}"
        run: npx puppeteer browsers install chrome

      - name: Install Tools
        run: npm ci --ignore-scripts && npx puppeteer browsers install chrome && bundle install

      - name: Run All Checks
        run: npm run check -- --lsConfig='-c .github/linkspector-local_check.yml'
        env:
          lsconfig: '-c .github/linkspector-local_check.yml'
