name: CI Contrib

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: &path_filters
      - "helpers/**"
      - "propagator/**"
      - "resources/**"
      - "processor/**"
      - "sampler/**"
      - ".github/workflows/ci-contrib.yml"
      - ".github/actions/**"
      - "Rakefile"
      - "gemspecs/**"
  pull_request:
    branches:
      - main
    paths: *path_filters
  merge_group:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }} # Ensure that only one instance of this workflow is running per event type and ref
  cancel-in-progress: true # Cancel any previous runs of this workflow for the same event type and ref

jobs:
  helpers:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    strategy:
      fail-fast: false
      matrix:
        gem:
          - helpers-mysql
          - helpers-sql
          - helpers-sql-processor
          - processor-baggage
          - propagator-google_cloud_trace_context
          - propagator-ottrace
          - propagator-vitess
          - propagator-xray
          - resource-detector-aws
          - resource-detector-azure
          - resource-detector-container
          - resource-detector-google_cloud_platform
          - sampler-xray
        os:
          - ubuntu-24.04
    name: "${{ matrix.gem }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: "Test Ruby 4.0"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-${{ matrix.gem }}"
          ruby: "4.0"
      - name: "Test Ruby 3.4"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-${{ matrix.gem }}"
          ruby: "3.4"
      - name: "Test Ruby 3.3"
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-${{ matrix.gem }}"
          ruby: "3.3"
          yard: true
          build: true
      - name: "Test JRuby"
        if: startsWith(matrix.os, 'ubuntu')
        uses: ./.github/actions/test_gem
        with:
          gem: "opentelemetry-${{ matrix.gem }}"
          ruby: "jruby-10.0.2.0"
