name: File Checks

on:
  pull_request:
  merge_group:

permissions:
  contents: read
  pull-requests: write # required for posting PR review comments

jobs:
  markdown-lint-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: Markdown Lint Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # equivalent cli: markdownlint-cli2  "**/*.md" "!**/CHANGELOG.md"  --config .markdownlint-cli2.yaml
      - name: "Markdown Lint Check"
        uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v22.0.0
        with:
          config: .markdownlint-cli2.yaml
          fix: false
          globs: |
            **/*.md

  markdown-link-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: Markdown Link Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # equivalent cli: linkspector check
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@37c85bcde51b30bf929936502bac6bfb7e8f0a4d # v1.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-annotations
          fail_on_error: true

  json-lint-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: JSON Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: "npm"
          node-version: "24"

      - name: install dependencies
        run: npm ci --ignore-scripts

      # equivalent cli: jsonlint --config ./.jsonlintrc.yml
      - name: "JSON Lint Check"
        run: npm run check:lint:json

  renovate-config-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: Renovate Config Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: "npm"
          node-version: "24"

      - name: install dependencies
        run: npm ci --ignore-scripts

      # equivalent cli: renovate-config-validator
      - name: "Renovate Lint Check"
        run: npm run check:lint:renovate

  ruby-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: RuboCop Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: "npm"
          node-version: "24"

      - name: Install Ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          ruby-version: "3.2.10"

      - name: Install Tools
        run: npm ci --ignore-scripts && bundle install

      - name: "Lint all ruby files"
        run: |
          set -e # forces exit code to propagate
          npm run check:lint:ruby -- --format github

      - name: "Check all ruby source files"
        run: |
          set -e # forces exit code to propagate
          npm run check:source:ruby -- --format github

  yaml-lint-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: YAML Lint Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # equivalent cli: yamllint .
      - name: "YAML Lint Check"
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c #v3.1.1
        with:
          config_file: .yamllint

  spelling-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: Spelling Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Extract PR title
        id: pr
        run: |
          echo "${{ github.event.pull_request.title }}" > pr_title.md
      - uses: streetsidesoftware/cspell-action@9cd41bb518a24fefdafd9880cbab8f0ceba04d28 # v8.3.0
        with:
          use_cspell_files: true
          config: .cspell.yml
          suggestions: true
          treat_flagged_words_as_errors: true

  format-check:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    name: File Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: "npm"
          node-version: "24"

      - name: Install Ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          ruby-version: "3.2.10"

      - name: Install Tools
        run: npm ci --ignore-scripts && bundle install

      - name: "Format all document Check"
        run: npm run write:format

      - name: validate files
        run: git diff --exit-code ':*.*' || (echo 'Files are out of date, please run "npm run write:format" and commit the changes in this PR.' && exit 1)
