# Workflows for CI, Yardocs, etc...
name: CI Misc

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  instrumentation:
    strategy:
      fail-fast: false
      matrix:
        gem:
          - propagator-ottrace
          - propagator-xray
          - instrumentation-que
          - instrumentation-http_client
          - instrumentation-mysql2
          - instrumentation-sinatra
          - instrumentation-sidekiq
          - instrumentation-dalli
          - instrumentation-racecar
          - instrumentation-redis
          - instrumentation-ruby_kafka
          - instrumentation-concurrent_ruby
          - instrumentation-active_model_serializers
          - instrumentation-rake
          - instrumentation-action_view
          - instrumentation-bunny
          - instrumentation-all
          - instrumentation-aws_sdk
          - instrumentation-active_record
          - instrumentation-faraday
          - instrumentation-resque
          - instrumentation-rdkafka
          - instrumentation-pg
          - instrumentation-ethon
          - instrumentation-lmdb
          - instrumentation-active_support
          - instrumentation-http
          - instrumentation-graphql
          - instrumentation-trilogy
          - instrumentation-net_http
          - instrumentation-rack
          - instrumentation-action_pack
          - instrumentation-mongo
          - instrumentation-restclient
          - instrumentation-koala
          - instrumentation-active_job
          - instrumentation-excon
          - instrumentation-rspec
          - instrumentation-base
          - instrumentation-delayed_job
          - instrumentation-rails
          - resource_detectors
        os:
          - ubuntu-latest

    name: ${{ matrix.gem }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "Build and yarddoc"
        uses: ./.github/actions/test_gem
        with:
          gem:  opentelemetry-${{ matrix.gem }}
          ruby: "2.7"
          yard: true
          rubocop: true
          build: true
          test: false
