name: Build

on:
  workflow_call:
    inputs:
      gems:
        required: true
        type: string

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}-build # Ensure that only one instance of this workflow is running per event type and ref
  cancel-in-progress: true # Cancel any previous runs of this workflow for the same event type and ref

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        gem: ${{ fromJson(inputs.gems) }}
        os:
          - ubuntu-24.04
        ruby:
          - ruby-3.3
      fail-fast: false
    name: "${{ matrix.gem }} / ${{matrix.os}} [${{ matrix.ruby }}]"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler: latest
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Restore Bundler Cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
        with:
          path: |
            vendor
            !vendor/bundle/cache
          key: bundler-${{ runner.os }}-${{ matrix.gem }}-${{ matrix.ruby }}-randomString
          restore-keys: |
            bundler-${{ runner.os }}-${{ matrix.gem }}-${{ matrix.ruby }}-
      - name: Install Tools & Gem Deps
        run: |
          # ⚙️ Install ⚙️
          bundle exec rake install
      - name: YARD
        shell: bash
        run: |
          # 📄 Yard Docs 📄
          bundle exec rake yard
      - name: Build Gem
        shell: bash
        run: |
          # 📦 Build Gem 📦
          bundle exec rake build
