---
name: Linter Conventional Commits
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: wagoid/commitlint-github-action@v5.4.5
        name: Lint Commit Messages
