name: File Review

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

permissions:
  contents: read

jobs:
  filesystem:
    uses: ./.github/workflows/file_review-filesystem.yml
  ci:
    uses: ./.github/workflows/file_review-ci_setup.yml
  checks:
    uses: ./.github/workflows/ci-markdown-checks.yml
    secrets:
      abc: ${{ secrets.GITHUB_TOKEN }}
