# This workflow is intended to catch issues with installation issues after a release
# If the jobs fail that means users will not be able to install the latest version of gems
# You may have to update and release gems that fail to install
name: Installation Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: &path_filters
      - ".github/workflows/installation-tests.yml"
      - "releases/**"
  pull_request:
    branches:
      - main
    paths: *path_filters
  schedule:
    # Everyday at 2 PM UTC
    - cron: "0 14 * * *"

permissions:
  contents: read

jobs:
  installation-tests:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 4.0
          - 3.4
          - 3.3
          - 3.2
    name: ${{ matrix.ruby-version }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ruby/setup-ruby@4eb9f110bac952a8b68ecf92e3b5c7a987594ba6 # v1.292.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: "Install Latest Gem Versions on ${{ matrix.ruby-version }}"
        working-directory: releases
        run: ./run.sh
  installation-latest-tests:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    strategy:
      fail-fast: false
    name: Latest
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ruby/setup-ruby@4eb9f110bac952a8b68ecf92e3b5c7a987594ba6 # v1.292.0
        with:
          ruby-version: 4.0.1
      - name: "Install Latest Gem Versions on Latest Ruby"
        working-directory: releases
        run: ./run.sh
