# This workflow is intended to catch issues with installation issues after a release
# If the jobs fail that means users will not be able to install the latest version of gems
# You may have to update and release gems that fail to install
name: Installation Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: &path_filters
      - ".github/workflows/installation-tests.yml"
      - "releases/**"
  pull_request:
    branches:
      - main
    paths: *path_filters
  schedule:
    # Everyday at 2 PM UTC
    - cron: "0 14 * * *"

permissions:
  contents: read

jobs:
  installation-tests:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 4.0
          - 3.4
          - 3.3
    name: ${{ matrix.ruby-version }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: "Install Latest Gem Versions on ${{ matrix.ruby-version }}"
        working-directory: releases
        run: ./run.sh
  installation-latest-tests:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    strategy:
      fail-fast: false
    name: Latest
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: "4.0.5"
      - name: "Install Latest Gem Versions on Latest Ruby"
        working-directory: releases
        run: ./run.sh
