name: "Lint Conventional Commits"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}  # Ensure that only one instance of this workflow is running per Pull Request
  cancel-in-progress: true  # Cancel any previous runs of this workflow

jobs:
  main:
    name: Lint Conventional Commits
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: amannn/action-semantic-pull-request@v5.4.0
        name: "🤖 Check PR title follows conventional commit spec"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Have to specify all types because `maint` and `rel` aren't defaults
          types: |
            fix
            feat
            chore
            ci
            docs
            style
            refactor
            perf
            test
      - uses: actions/checkout@v4.1.1
      - uses: wagoid/commitlint-github-action@v5.4.5
        name: "🤖 Check commit messages follow conventional commit spec"
