name: "[release hook] Update open releases"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-update-open-requests:
    permissions:
      contents: write # required for updating releases
      pull-requests: write # required for updating release PRs
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    runs-on: ubuntu-24.04
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/.toys/release/Gemfile
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Ruby
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          ruby-version: "4.0.5"
          bundler-cache: true
      - name: Update open releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec toys release _onpush --verbose \
            < /dev/null
