name: Open release request

on:
  workflow_dispatch:
    inputs:
      names:
        description: Components to release (leave blank to release all components)
        required: false
        default: ""

permissions:
  contents: read

jobs:
  release-request:
    permissions:
      contents: write # required for creating releases
      pull-requests: write # required for creating release PRs
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    runs-on: ubuntu-24.04
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/.toys/release/Gemfile
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Ruby
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          ruby-version: "4.0.6"
          bundler-cache: true

      - name: Create otelbot app token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.OTELBOT_RUBY_CONTRIB_CLIENT_ID }}
          private-key: ${{ secrets.OTELBOT_RUBY_CONTRIB_PRIVATE_KEY }}

      - name: Open release pull request
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          TARGET_BRANCH: ${{ github.ref }}
          RELEASE_NAMES: ${{ github.event.inputs.names }}
        run: |
          bundle exec toys release request --yes --verbose \
            "--target-branch=$TARGET_BRANCH" \
            $RELEASE_NAMES \
            < /dev/null
