name: "[release hook] Update open releases"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-update-open-requests:
    permissions:
      contents: write # required for updating releases
      pull-requests: write # required for updating release PRs
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    runs-on: ubuntu-24.04
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/.toys/release/Gemfile
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: "4.0.5"
          bundler-cache: true
      - name: Update open releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec toys release _onpush --verbose \
            < /dev/null
