name: "[release hook] Process release"

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  release-process-request:
    permissions:
      contents: write # required for creating releases
      pull-requests: write # required for updating release PRs
      issues: write # required to create issues for failed releases
    if: ${{ github.repository == 'open-telemetry/opentelemetry-ruby-contrib' }}
    runs-on: ubuntu-24.04
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/.toys/release/Gemfile
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: "4.0.5"
          bundler-cache: true
      - name: Process release request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          bundle exec toys release _onclosed --verbose \
            "--event-path=${{ github.event_path }}" \
            < /dev/null
